# Generated by Django 5.2.8 on 2025-11-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VanityAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum (ERC-20 / USDT)'), ('ltc', 'Litecoin'), ('doge', 'Dogecoin'), ('sol', 'Solana'), ('tron', 'Tron(TRX / USDT-TRC20)')], max_length=10)),
                ('prefix', models.CharField(blank=True, max_length=64)),
                ('suffix', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(max_length=300)),
                ('private_key', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
