# Generated by Django 5.2.8 on 2025-11-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vanityaddress',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='vanityaddress',
            name='blockchain',
        ),
        migrations.AlterField(
            model_name='vanityaddress',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='vanityaddress',
            name='prefix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vanityaddress',
            name='private_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vanityaddress',
            name='suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
